algoritmo "QUESTAO4"

//Desenvolva um algoritmo que leia dois números inteiros e mostre o somatório
//entre eles.
//Ex:
//Digite um valor: 8
//Digite outro valor: 5
//A soma entre 8 e 5 é igual a 13.
var
   n1, n2, soma: inteiro
inicio

   escreval ("Informe um valor: ")
   leia (n1)
   escreval ("Informe outro valor: ")
   leia (n2)

   soma <- n1 + n2

   escreval ("----------------------------------------------")
   escreval ("A soma entre", n1, " e", n2, " é igual a", soma)

fimalgoritmo